#!/usr/bin/env bash
#  Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself):
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
/etc/init.d/nginx start
